### ISSUE TITLE
love the project, update to nugets and build, 

### ISSUE THREAD

**Issue by weedkiller** [dotnetreport/dotnetreport#2]
hi, very nice project love it :hea, any chance we can integrate jquery [builder](https://querybuilder.js.org/) or [QT](https://github.com/d4software/QueryTree) and allow chaning of chart types

also a simple fix would be Bootstrap 4.1 and nuget updates.  I had trouble navigating to the setup page, got errors after my connection was fixed. I was able to fix these easily below (kust wanted to let you know out of the bag, some errors others may run into)

![image](https://user-images.githubusercontent.com/21086190/47609812-3947ad80-da14-11e8-94b9-1b47df863d8d.png)

per documentation page ==> dotnetreport page

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

![image](https://user-images.githubusercontent.com/21086190/47609840-cab71f80-da14-11e8-923b-68c6c8a7d647.png)

**Comment by dotnetreport** [comment]
Thanks for the comment, glad you love the project. For the query builder, were already working on something similar to let user build better filters. Take a look a this branch: https://github.com/dotnetreport/ReportBuilder.Web/tree/feature/group-filter. The UI is done, but the backend service is still being worked on. 

As for the 2 screenshots, seems like you navigated to the wrong url, will check/update documentation if it's wrong. The other screenshot is going to Report directly, instead of navigating it to by running the report, hence the error.

**Comment by weedkiller** [comment]
how to navigate or see the backend table configuration admin page...
